# Generated by Django 5.1.7 on 2025-05-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_date_event_end_date_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('dorm', 'Dorm'), ('library', 'Library'), ('lab', 'Lab'), ('classroom', 'Classroom'), ('office', 'Office'), ('cafe', 'Cafe'), ('fun and games', ' Fun and Games'), ('shop', 'Shop'), ('other', 'Other')], max_length=20),
        ),
    ]
